<a href="https://colab.research.google.com/github/tanishq252/Traffic_Sign_Recognition_using_CNN_and_ANN/blob/master/ANN_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
train_inputs = np.array([[0,0,1],
                        [1,1,1],
                        [1,0,1],
                        [0,1,1]])

In [ ]:
train_outputs = np.array([[0,1,1,0]]).T

In [ ]:
np.random.seed(1) #for getting same weights

In [ ]:
# so here epsilon value is 1 so as to get random integers between (-1,1)
_weights = 2*np.random.random((3,1)) - 1

In [ ]:
_weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [ ]:
# here we have loops so as to get backprop done where iteration number can be said to epoch
 
for epoch in range(2):
 
  input_layer = train_inputs
 
  output_layer  = train_outputs
 
  predicted_output = sigmoid(np.dot(input_layer,_weights)) # here look at the dimensions and keep in mind we want the dimensions same as the output layer

In [ ]:
predicted_output

array([[0.2689864 ],
       [0.3262757 ],
       [0.23762817],
       [0.36375058]])

In [ ]:
#  here we can see that model is messed up

In [ ]:
#  so let us start with backprop 

In [ ]:
""" so using gradient descent the derivative of cost function where we use sigmoid
 as activation function is gonna look like :
adjustment = error X sigmoid'(output) X input
"""

" so using gradient descent the derivative of cost function where we use sigmoid\n as activation function is gonna look like :\nadjusted_weight = error X sigmoid'(output) X input"

In [ ]:
# adding a sigmoid derivative function
def sigmoid_derivative(x):
  return x * (1-x)

In [ ]:
for epoch in range(2):
 
  input_layer = train_inputs
 
  output_layer  = train_outputs
 
  predicted_output = sigmoid(np.dot(input_layer,_weights))
  
  error = output_layer - predicted_output
 
  adjustment = error*sigmoid_derivative(predicted_output) # as we pass sigmoid output the function is simply returning the value as derivative format
 
  _weights += np.dot(input_layer.T,adjustment) # here also keep an eye on dimensions
 
print(predicted_output)

[[0.00213544]
 [0.99825848]
 [0.99858574]
 [0.00173429]]


In [ ]:
# so we are updating the weights so let us run for 100,200,1000,2000 times and see results

In [ ]:
for epoch in range(100):
 
  input_layer = train_inputs
 
  output_layer  = train_outputs
 
  predicted_output = sigmoid(np.dot(input_layer,_weights))
  
  error = output_layer - predicted_output
 
  adjustment = error*sigmoid_derivative(predicted_output) 
 
  _weights += np.dot(input_layer.T,adjustment)
 
print(predicted_output)

[[0.11328454]
 [0.90801039]
 [0.92344514]
 [0.0946492 ]]


In [ ]:
for epoch in range(200):
 
  input_layer = train_inputs
 
  output_layer  = train_outputs
 
  predicted_output = sigmoid(np.dot(input_layer,_weights))
  
  error = output_layer - predicted_output
 
  adjustment = error*sigmoid_derivative(predicted_output) 
 
  _weights += np.dot(input_layer.T,adjustment)
 
print(predicted_output)

[[0.00213545]
 [0.99825847]
 [0.99858573]
 [0.00173429]]


In [ ]:
for epoch in range(2000):

  input_layer = train_inputs

  output_layer  = train_outputs

  predicted_output = sigmoid(np.dot(input_layer,_weights))
  
  error = output_layer - predicted_output

  adjustment = error*sigmoid_derivative(predicted_output) 

  _weights += np.dot(input_layer.T,adjustment)

print(predicted_output)

[[0.0205307 ]
 [0.98328124]
 [0.98643907]
 [0.01666508]]


In [ ]:
for epoch in range(200000):
 
  input_layer = train_inputs
 
  output_layer  = train_outputs
 
  predicted_output = sigmoid(np.dot(input_layer,_weights))
  
  error = output_layer - predicted_output
 
  adjustment = error*sigmoid_derivative(predicted_output) 
 
  _weights += np.dot(input_layer.T,adjustment)
 
print(predicted_output)

[[0.00213653]
 [0.99825759]
 [0.99858503]
 [0.00173516]]


In [ ]:
# so we can see as we train data more and more using more epochs we get predicted outputs as we initialized
# as we know for sigmoid : output>=0.5 is 1 and output<0.5 is 0

In [ ]:
_predictions = []

for i in predicted_output:
  if i>=0.5:
    _predictions.append(1)
  else:
    _predictions.append(0)

print(_predictions)


[0, 1, 1, 0]


In [ ]:
#  ;) as expected